# Generated by Django 4.2.6 on 2024-03-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_inventory_max_capacity_inventory_min_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='size',
            field=models.CharField(choices=[('25.5cm', 'US 7.5'), ('26cm', 'US 8'), ('26.5cm', 'US 8.5'), ('27cm', 'US 9'), ('27.5cm', 'US 9.5'), ('28cm', 'US 10'), ('28.5cm', 'US 10.5'), ('29cm', 'US 11'), ('29.5cm', 'US 11.5'), ('30cm', 'US 12')], max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('25.5cm', 'US 7.5'), ('26cm', 'US 8'), ('26.5cm', 'US 8.5'), ('27cm', 'US 9'), ('27.5cm', 'US 9.5'), ('28cm', 'US 10'), ('28.5cm', 'US 10.5'), ('29cm', 'US 11'), ('29.5cm', 'US 11.5'), ('30cm', 'US 12')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('25.5cm', 'US 7.5'), ('26cm', 'US 8'), ('26.5cm', 'US 8.5'), ('27cm', 'US 9'), ('27.5cm', 'US 9.5'), ('28cm', 'US 10'), ('28.5cm', 'US 10.5'), ('29cm', 'US 11'), ('29.5cm', 'US 11.5'), ('30cm', 'US 12')], max_length=10),
        ),
    ]
