# Generated by Django 5.0.4 on 2024-04-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_emailaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
