# Generated by Django 4.2.6 on 2024-06-05 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_member_gender_alter_member_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='PRO001', max_length=50, unique=False, verbose_name='商品編號'),
        ),

        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': '庫存', 'verbose_name_plural': '庫存'},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='max_capacity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='min_order_quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='庫存量'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='1.png', upload_to='product_photos/', verbose_name='照片'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='PRO001', max_length=50, unique=False, verbose_name='商品編號'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='products.product', verbose_name='商品編號'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='size',
            field=models.CharField(choices=[('25.5cm', 'US 7.5'), ('26cm', 'US 8'), ('26.5cm', 'US 8.5'), ('27cm', 'US 9'), ('27.5cm', 'US 9.5'), ('28cm', 'US 10'), ('28.5cm', 'US 10.5'), ('29cm', 'US 11'), ('29.5cm', 'US 11.5'), ('30cm', 'US 12')], max_length=10, verbose_name='尺寸'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=255, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='商品介紹'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='商品名稱'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品價格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('25.5cm', 'US 7.5'), ('26cm', 'US 8'), ('26.5cm', 'US 8.5'), ('27cm', 'US 9'), ('27.5cm', 'US 9.5'), ('28cm', 'US 10'), ('28.5cm', 'US 10.5'), ('29cm', 'US 11'), ('29.5cm', 'US 11.5'), ('30cm', 'US 12')], max_length=10, verbose_name='尺寸'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_code', models.CharField(max_length=50, unique=True, verbose_name='回饋編號')),
                ('comment', models.TextField(verbose_name='留言')),
                ('product_satisfaction', models.PositiveIntegerField(default=5, verbose_name='商品滿意度')),
                ('brand_satisfaction', models.PositiveIntegerField(default=5, verbose_name='品牌滿意度')),
                ('delivery_satisfaction', models.PositiveIntegerField(default=5, verbose_name='宅配滿意度')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='products.member', verbose_name='客戶編號')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='products.product', verbose_name='商品名稱')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=50, unique=True, verbose_name='訂單編號')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='價格')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='總價')),
                ('quantity', models.PositiveIntegerField(verbose_name='數量')),
                ('shipping_address', models.CharField(max_length=255, verbose_name='運送地址')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='products.inventory', verbose_name='產品編號')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='products.member', verbose_name='顧客編號')),
            ],
        ),
    ]
