# Generated by Django 4.2.6 on 2024-06-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='PRO000', max_length=50, unique=False, verbose_name='商品編號'),
        ),
    ]
