# Generated by Django 4.2.6 on 2024-06-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='product_photos/', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='PRO000', max_length=50, unique=False, verbose_name='商品編號'),
        ),
    ]
