# Generated by Django 4.2.6 on 2024-06-06 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_product_photo_alter_product_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
